### ISSUE TITLE
Import error when testing pyquat 

### ISSUE THREAD

**Issue by WillFife** [mohawkjohn/pyquat#1]
When testing successful installation of pyquat, I ran into an ImportError stating "No module named _pyquat." The problem is that pyquat cannot be used in python scripts that are in the same directory as the pyquat package. A quick round-about fix is to work in the parent directory of where the pyquat package is located. Doing this, you should successfully be able to import the pyquat package into your scripts.

**Comment by mohawkjohn** [comment]
I believe this is fixed, but please feel free to reopen if the problem becomes apparent again.
